Updates

diff --git a/.github/workflows/deploy-stage.yaml b/.github/workflows/deploy-stage.yaml
--- a/.github/workflows/deploy-stage.yaml
+++ b/.github/workflows/deploy-stage.yaml
@@ -11,6 +11,12 @@ on: [push]
 #    types:
 #      - completed
 
+
+env:
+  APP_NAME: hello-world
+  APP_PORT: 80
+  OPENSHIFT_NAMESPACE: davidher28-dev
+
 jobs:
   publish:
     runs-on: ubuntu-22.04
@@ -27,7 +33,7 @@ jobs:
 
       # ------------------------------- Docker Build and Push ------------------------------- #
       - name: Login to Docker Hub
-        id: login
+        id: docker_login
         uses: docker/login-action@v3
         with:
           username: ${{ secrets.DOCKERHUB_USERNAME }}
@@ -57,22 +63,45 @@ jobs:
           tag: ${{ steps.tagging.outputs.new_tag }}
 
       # ------------------------------- Red Hat OpenShift Deployment ------------------------------- #
-      - name: Install OpenShift CLI
-        uses: redhat-actions/oc-installer@v1
-        with:
-          oc_version: '4.6'
-
       - name: Log in to OpenShift
+        id: oc_login
         uses: redhat-actions/oc-login@v1
         with:
           openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
           openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
 
       - name: Create and expose app
+        id: oc_deploy
         env:
           IMAGE_REPOSITORY: ${{ secrets.DOCKERHUB_USERNAME }}
           IMAGE_TAG: ${{ steps.tagging.outputs.new_tag }}
         run: |
-          sed -i "s|$DOCKER_IMAGE|$IMAGE_REPOSITORY/fastapi:$IMAGE_TAG|g" ./kubernetes/deployment.yaml && \
-          oc create -f ./kubernetes/deployment.yaml
-          oc apply -f ./kubernetes/service.yaml
+          export IMAGE="$IMAGE_REPOSITORY/fastapi:$IMAGE_TAG"
+          export PORT=${{ env.APP_PORT }}
+
+          export SELECTOR="app=${{ env.APP_NAME }}"
+          echo "SELECTOR=$SELECTOR" >> $GITHUB_ENV
+
+          set -x
+          # Take down any old deployment
+          oc delete all --selector="$SELECTOR"
+          oc new-app --name $APP_NAME --docker-image="$IMAGE"
+
+          oc patch svc $APP_NAME -p "{ \"spec\": { \"ports\": [{ \"name\": \"$PORT-tcp\", \"port\": $PORT }] } }"
+          oc expose service $APP_NAME --port=$PORT
+
+          oc get all --selector="$SELECTOR"
+          set +x
+
+          export ROUTE="$(oc get route $APP_NAME -o jsonpath='{.spec.host}')"
+          echo "$APP_NAME is exposed at $ROUTE"
+          echo "ROUTE=$ROUTE" >> $GITHUB_ENV
+
+      - name: View application route
+        run: |
+          [[ -n ${{ env.ROUTE }} ]] || (echo "Determining application route failed in previous step"; exit 1)
+          echo "======================== Your application is available at: ========================"
+          echo ${{ env.ROUTE }}
+          echo "==================================================================================="
+          echo
+          echo "Your app can be taken down with: \"oc delete all --selector='${{ env.SELECTOR }}'\""
