#patch Testing Deployment (#46)

diff --git a/.github/workflows/deploy-stage.yaml b/.github/workflows/deploy-stage.yaml
--- a/.github/workflows/deploy-stage.yaml
+++ b/.github/workflows/deploy-stage.yaml
@@ -1,13 +1,19 @@
 name: Deploy Stage
 
 on:
-  workflow_run:
-    workflows:
-      - 'Commit Stage'
-    branches:
-      - 'main'
-    types:
-      - completed
+ workflow_run:
+   workflows:
+     - 'Commit Stage'
+   branches:
+     - main
+   types:
+     - completed
+
+
+env:
+  APP_NAME: hello-world
+  APP_PORT: 8080
+  OPENSHIFT_NAMESPACE: davidher28-dev
 
 jobs:
   publish:
@@ -15,18 +21,20 @@ jobs:
     steps:
       - uses: actions/checkout@v4
 
-      - name: Bump Version and Push Tag
+      # ------------------------------- Application Versioning ------------------------------- #
+      - name: Bump Application Version and Push Tag
         id: tagging
         uses: anothrNick/github-tag-action@1.64.0
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           WITH_V: true
 
+      # ------------------------------- Docker Build and Push ------------------------------- #
       - name: Login to Docker Hub
-        id: login
+        id: docker_login
         uses: docker/login-action@v3
         with:
-          username: ${{ secrets.DOCKERHUB_USERNAME }}
+          username: ${{ vars.DOCKERHUB_USERNAME }}
           password: ${{ secrets.DOCKERHUB_TOKEN }}
 
       - name: Set up Docker Buildx
@@ -39,34 +47,61 @@ jobs:
           context: .
           file: ./docker/Dockerfile
           push: ${{ github.event_name != 'pull_request' }}
-          tags: ${{ secrets.DOCKERHUB_USERNAME }}/fastapi:${{ steps.tagging.outputs.new_tag }}
+          tags: ${{ vars.DOCKERHUB_USERNAME }}/fastapi:${{ steps.tagging.outputs.new_tag }}
 
       - name: Docker Image digest
         run: echo ${{ steps.docker_build.outputs.digest }}
 
+      # ------------------------------- GitHub Release ------------------------------- #
       - name: Create a GitHub Release
         id: create_release
         uses: ncipollo/release-action@v1
         with:
           name: Release ${{ steps.tagging.outputs.new_tag }}
           tag: ${{ steps.tagging.outputs.new_tag }}
+          allowUpdates: true
 
-      - name: Install OpenShift CLI
-        uses: redhat-actions/oc-installer@v1
-        with:
-          oc_version: '4.6'
-
+      # ------------------------------- Red Hat OpenShift Deployment ------------------------------- #
       - name: Log in to OpenShift
+        id: oc_login
         uses: redhat-actions/oc-login@v1
         with:
           openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
           openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
+          namespace: ${{ env.OPENSHIFT_NAMESPACE }}
 
       - name: Create and expose app
+        id: deploy-and-expose
+        uses: redhat-actions/oc-new-app@v1
         env:
-          IMAGE_REPOSITORY: ${{ secrets.DOCKERHUB_USERNAME }}
+          IMAGE_REPOSITORY: ${{ vars.DOCKERHUB_USERNAME }}
           IMAGE_TAG: ${{ steps.tagging.outputs.new_tag }}
+        with:
+          app_name: ${{ env.APP_NAME }}
+          image: docker.io/${{ vars.DOCKERHUB_USERNAME }}/fastapi:${{ steps.tagging.outputs.new_tag }}
+          namespace: ${{ env.OPENSHIFT_NAMESPACE }}
+          port: ${{ env.APP_PORT }}
+
+      - name: View application route
+        id: view_application_route
+        env:
+          ROUTE: ${{ steps.deploy-and-expose.outputs.route }}
+          SELECTOR: ${{ steps.deploy-and-expose.outputs.selector }}
         run: |
-          sed -i "s|$DOCKER_IMAGE|$IMAGE_REPOSITORY/fastapi:$IMAGE_TAG|g" ./kubernetes/deployment.yaml && \
-          oc apply -f ./kubernetes/deployment.yaml
-          oc apply -f ./kubernetes/service.yaml
+          [[ -n ${{ env.ROUTE }} ]] || (echo "Determining application route failed in previous step"; exit 1)
+          echo "======================== The application is available at: ========================"
+          echo ${{ env.ROUTE }}
+          echo "==================================================================================="
+          echo
+          echo "It can be taken down with: \"oc delete all --selector='${{ env.SELECTOR }}'\""
+
+      # ------------------------------- Deployment Test ------------------------------- #
+      - name: Test project is deployed
+        id: test_deploy
+        uses: nick-invision/retry@v3
+        with:
+          timeout_seconds: 3
+          retry_wait_seconds: 10
+          max_attempts: 30
+          warning_on_retry: false
+          command: curl -sSfLi ${{ steps.deploy-and-expose.outputs.route }}
